### ISSUE TITLE
same script for aac files?

### ISSUE THREAD

**Issue by thedkm** [siteuser42/clunky-audiobook-chapterizing#13]
can u make same script for aac files?

**Comment by TheMetalCenter** [comment]
Hmm, I've never worked with aac files. However, aac is often the audio codec used in a mp4/m4a/m4b file. I don't know if aac files supports any chapter tags by itself, but I would guess that it would be easy to wrap the aac file into a m4b container without re-encoding the file (i.e. without quality loss.). 

Something like "ffmpeg -i input.aac -c copy output.mp4" would probably work. Then continue using these scripts for an mp4 like normal.

**Comment by thedkm** [comment]
yeah exactly aac is the audio codec in m4b, and merging all aac files into single M4b without quality loss thats what I need . Please try If u can make aac to m4b merging script , thanks.

**Comment by TheMetalCenter** [comment]
Gotcha, I can look into it. I think it will be straightforward but will have to test it out.

**Comment by thedkm** [comment]
sure, Please try these aac files https://bashupload.com/IppBz/Main.rar

**Comment by TheMetalCenter** [comment]
Your link says 404 no file; I think I found some to test with though

**Comment by TheMetalCenter** [comment]
added "aac_merge-files.bat" to optional scripts folder. Tested it and it seems to work. Essentially you just follow scenario 1 or scenario 4 instructions, except use "aac_merge-files.bat" instead of "m4b_merge-files.bat".

**Comment by thedkm** [comment]
ohh wow much thanks will test it out.

**Comment by thedkm** [comment]
Press [q] to stop, [?] for help
filelist.txt: I/O error:00:00.00 bitrate=N/A speed=   0x

it gives me erros like this , did u try with files I have sent u??https://bashupload.com/SnE7N/Main.rar

**Comment by TheMetalCenter** [comment]
No, the first link was broken. I just tried with the ones in the second link, and yeah something is up with these files. It is unrelated to the script, if I use ffmpeg on the first aac file it gives an I/O error. The second does not give an error. The 3rd, 4th, and 5th, do. The 6th does not. I think the files may be corrupted, I/O means a read/write error.

**Comment by TheMetalCenter** [comment]
Strangely using ffmpeg on the individual files still spits out the wrapped mp4 despite the error message. So you could use ffmpeg on each file then merge them with m4b_merge-files.bat after changing mp4 extension to m4b. Annoying workaround if you have multiple books you need to do this on, but not too bad for a one time fix.

**Comment by thedkm** [comment]
well these files are from Scribd n it gave files in like thousands 😆 , so like processing file one by one is not possible , thats why I wanted a merging script so I can merge these thousands of file into single M4b anyway thanks for all the work.

**Comment by TheMetalCenter** [comment]
I added a batch script called aac2m4b in optional folder that converts all aac files in a directory to m4b, then you can merge with m4b_merge-files. It seems to have worked okay on the 11 files you uploaded. Best of luck!

**Comment by thedkm** [comment]
thanks for the efforts.
