### ISSUE TITLE
bat files can't pass files with special language characters 

### ISSUE THREAD

**Issue by TheMetalCenter** [siteuser42/clunky-audiobook-chapterizing#3]
For example,

Alice's Adventures in Wonderland (1).mp3 would not be passed on.

FFmpeg will give an error about file not being found (looks for 'Alice'

**Comment by TheMetalCenter** [comment]
Exclamation points also not accepted
Guards! Guards!.mp3 for example

**Comment by TheMetalCenter** [comment]
Solved for apostrophe

**Comment by TheMetalCenter** [comment]
& is also an issue

**Comment by TheMetalCenter** [comment]
Fixed for & and !

**Comment by TheMetalCenter** [comment]
Every other usual special character seems to be working, so tentatively closing this until I come across one that doesn't.

**Comment by TheMetalCenter** [comment]
Well that was fast, language special characters still not working (for example ó). Probably won't fix this, too many to worry about.

**Comment by siteuser42** [comment]
This seems to have been fixed when switching from TexttoCue.exe to lis2cue.py. A text encoding issue? The ticket will be re-opened if it is encountered again.

**Comment by TheMetalCenter** [comment]
Added chcp 65001>nul to enforce utf-8 encoding. Solved language character issues and issues with " & ". Conflicts still with " ! " and " ' " so will continue to auto-remove those from filenames.
